### PR TITLE
Finished parsing the accelerator data and fixed a vendor specific print alignment.

### PR DESCRIPTION
**Pull request by amaier17**
Finished parsing the accelerator interface data, added a human_readable option to the eideticom plugin for the status parsing. Fixed the human_readable printing alignment error when printing out vendor specific data in the normal identify namespace command with (-vH) options.

### CODE REVIEW

**Comment by sbates130272** [comment]
Can you resubmit these with a valid user-name? Also please take out the change to NVMe-print.c and send that one directly to upstream and to me as a separate Patch. That makes merging easier.

**Comment by amaier17** [comment]
Oh weird. Three username looked right when I created the pull request. I'll repush without the cli fix.

**Comment by amaier17** [comment]
Fixed! I believe it's changed so that each repo will use its own credentials now as well

**Comment by amaier17** [comment]
Fixed the whitespace and commit issues

**Pull request closed without merging**
